"""init-db

Revision ID: b29c812b8c7f
Revises:
Create Date: 2026-03-24 22:19:03.704574

"""

import typing

import sqlalchemy as sa

from alembic import op
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = "b29c812b8c7f"
down_revision: typing.Union[str, None] = None
branch_labels: typing.Union[str, typing.Sequence[str], None] = None
depends_on: typing.Union[str, typing.Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "outbox",
        sa.Column("id", sa.String(length=2048), nullable=False),
        sa.Column("topic", sa.String(length=2048), nullable=False),
        sa.Column("errors", sa.Integer(), nullable=False),
        sa.Column("created", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated", sa.DateTime(timezone=True), nullable=False),
        sa.Column("published", sa.DateTime(timezone=True), nullable=True),
        sa.Column("accepted", sa.DateTime(timezone=True), nullable=True),
        sa.Column("failed", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed", sa.DateTime(timezone=True), nullable=True),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "payments",
        sa.Column("id", sa.String(length=2048), nullable=False),
        sa.Column("amount", sa.String(length=2048), nullable=False),
        sa.Column("currency", sa.String(length=2048), nullable=False),
        sa.Column("description", sa.String(length=16384), nullable=True),
        sa.Column("status", sa.String(length=2048), nullable=False),
        sa.Column("idempotency_key", sa.String(length=2048), nullable=False),
        sa.Column("webhook_url", sa.String(length=2048), nullable=False),
        sa.Column("processed", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated", sa.DateTime(timezone=True), nullable=False),
        sa.Column("context", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("idempotency_key"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("payments")
    op.drop_table("outbox")
    # ### end Alembic commands ###
